networks:
  default:
    driver: bridge
  proxy:
    external: true

secrets:
  postgres:
    file: ${nextcloud}/secrets/postgres
  postgres-snappymail:
    file: ${nextcloud}/secrets/postgres-snappymail
  code:
    file: ${nextcloud}/secrets/code

services:
  nextcloud-postgres:
    image: postgres:14
    container_name: nextcloud-postgres
    restart: always
    volumes:
      - ${nextcloud}/db/postgres:/var/lib/postgresql/data
      - ${nextcloud}/db/backup:/backup
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_PASSWORD=${postgres-password}
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
    networks:
      - default
    secrets:
      - postgres

  nextcloud-postgres-snappymail:
    image: postgres:14
    container_name: nextcloud-postgres-snappymail
    restart: always
    volumes:
      - ${nextcloud}/db/postgres-snappymail:/var/lib/postgresql/data
      - ${nextcloud}/db/backup-snappymail:/backup
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_PASSWORD=${postgres-snappymail-password}
      - POSTGRES_USER=nextcloud-snappymail
      - POSTGRES_DB=nextcloud-snappymail
    networks:
      - default
    secrets:
      - postgres-snappymail

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: always
    command: ["--databases", "1", "--maxmemory-policy", "allkeys-lru", "--maxmemory", "${memory}"]
    volumes:
      - ${nextcloud}/nextcloud-redis:/data
    environment:
      - TZ=Asia/Jakarta
    networks:
      - default

  nextcloud-code:
    image: collabora/code:latest
    container_name: nextcloud-code
    restart: always
    privileged: true
    cap_add:
      - mknod
    environment:
      - 'TZ=Asia/Jakarta'
      - 'username=admin'
      - 'password=${code-password}'
      - 'aliasgroup1=https://${URL}:443'
      - 'dictionaries=id'
      - 'extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:mount_jail_tree=false --o:logging.level=warning --o:home_mode.enable=true --o:remote_font_config.url=https://${URL}/apps/richdocuments/settings/fonts.json'
    networks:
      - proxy
    dns:
      - ${IP}
    secrets:
      - code

  nextcloud-server:
    image: marcus1pierce/nextcloud:28-fpm-arm64
    container_name: nextcloud-server
    restart: always
    depends_on:
      - nextcloud-postgres
      - nextcloud-postgres-snappymail
      - nextcloud-redis
      - nextcloud-imaginary
    networks:
      - proxy
      - default
    volumes:
      - ${nextcloud}/server:/var/www/html
      - ${nextcloud}/nextcloud_data:/var/www/html/data
      - ${nextcloud}/tmp:/tmp
      - ${nextcloud}/conf/nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - ${nextcloud}/conf/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
      - ${nextcloud}/conf/www2.conf:/usr/local/etc/php-fpm.d/www2.conf:ro
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${postgres-password}
      - POSTGRES_HOST=nextcloud-postgres
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST=nextcloud-redis
    dns:
      - ${IP}
    secrets:
      - postgres

  nextcloud-cron:
    image: marcus1pierce/nextcloud:28-fpm-arm64
    container_name: nextcloud-cron
    restart: always
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-server
    networks:
      - default
    volumes:
      - ${nextcloud}/server:/var/www/html
      - ${nextcloud}/nextcloud_data:/var/www/html/data
      - ${nextcloud}/tmp:/tmp
      - ${nextcloud}/conf/nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - ${nextcloud}/conf/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
      - ${nextcloud}/conf/www2.conf:/usr/local/etc/php-fpm.d/www2.conf:ro

  nextcloud-notify-push:
    image: nextcloud:28-fpm
    container_name: nextcloud-notify-push
    restart: always
    entrypoint: /var/www/html/custom_apps/notify_push/bin/aarch64/notify_push /var/www/html/config/config.php
    networks:
      - default
      - proxy
    ports:
      - 7867:7867
    depends_on:
      - nextcloud-postgres
      - nextcloud-postgres-snappymail
      - nextcloud-redis
      - nextcloud-server
    environment:
      - TZ=Asia/Jakarta
      - PORT=7867
      - NEXTCLOUD_URL=https://${URL}
    volumes:
      - ${nextcloud}/server:/var/www/html
      - ${nextcloud}/nextcloud_data:/var/www/html/data
    dns:
      - ${IP}

  nextcloud-imaginary:
    image: nextcloud/aio-imaginary:latest
    container_name: nextcloud-imaginary
    restart: always
    expose:
      - "9000"
    environment:
      - TZ=Asia/Jakarta
    cap_add:
      - SYS_NICE
    networks:
      - default
